// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseUrl, supabasePublishableKey} from '../../constants/app-constants';

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey);